version: "3.7"

services:
    database:
        image: mysql:5.7
        ports:
            - "3037:3036"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=financial
        volumes:
            - alura-db:/var/lib/mysql

volumes:
    alura-db:
