version: "3.7"

services:
    api:
        image: php:8.1-apache
        container_name: api
        restart: always
        working_dir: /src
        volumes:
            - ./:/src
        ports:
            - "8100:8100"
        expose:
            - "8100"

    database:
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=financial
        volumes:
            - alura-db:/var/lib/mysql
        restart: always

volumes:
    alura-db:
